#!/usr/bin/env python3
"""Install the local LaMa weights used by Diorama (no system changes).

Requires a Python environment with torch, numpy and Pillow for inference.
Model source/checksum: Sanster/IOPaint, iopaint/model/lama.py.
"""

import hashlib
import os
from pathlib import Path
import sys
import tempfile
import urllib.request

URL = "https://github.com/Sanster/models/releases/download/add_big_lama/big-lama.pt"
MD5 = "e3aa4aaa15225a33ec84f9f4bc47e500"


def checksum(path):
    with path.open("rb") as file:
        return hashlib.file_digest(file, "md5").hexdigest()


def runtime_config_path():
    config = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return Path(os.environ.get("DIORAMA_LAMA_RUNTIME_CONFIG", config / "diorama/lama-runtime.conf"))


def configure_runtime():
    """Remember the interpreter that has the worker's offline dependencies."""
    try:
        import numpy  # noqa: F401
        import torch  # noqa: F401
        from PIL import Image  # noqa: F401
    except ImportError as error:
        raise RuntimeError(
            "LaMa requires Python with torch, numpy and Pillow; rerun this script with that Python"
        ) from error
    config = runtime_config_path()
    config.parent.mkdir(parents=True, exist_ok=True)
    # Keep the invoked executable path, including a venv symlink. Resolving it
    # can silently select the base interpreter without the installed packages.
    python = Path(os.path.abspath(sys.executable))
    library_path = os.environ.get("LD_LIBRARY_PATH")
    with tempfile.NamedTemporaryFile(
        dir=config.parent, mode="w", encoding="utf-8", delete=False
    ) as temporary:
        temporary.write("# Generated by Diorama's setup-lama.py\n")
        temporary.write(f"python={python}\n")
        if library_path:
            temporary.write(f"library_path={library_path}\n")
        temporary_path = Path(temporary.name)
    temporary_path.replace(config)
    print(f"LaMa Python configured: {python}")


def main():
    cache = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
    destination = Path(os.environ.get("DIORAMA_LAMA_MODEL", cache / "diorama/big-lama.pt"))
    if destination.is_file() and checksum(destination) == MD5:
        print(f"LaMa model already verified: {destination}")
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(dir=destination.parent, delete=False) as target:
                temporary = Path(target.name)
                print(f"Downloading LaMa to {destination}", flush=True)
                with urllib.request.urlopen(URL, timeout=60) as source:
                    while block := source.read(1024 * 1024):
                        target.write(block)
            if checksum(temporary) != MD5:
                raise RuntimeError("LaMa download checksum mismatch; existing model was not replaced")
            temporary.replace(destination)
            print(f"Verified LaMa model: {destination}")
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)
    configure_runtime()


if __name__ == "__main__":
    main()
